
name: E2E Test Suite
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: yarn install
    - name: Cypress
      uses: cypress-io/github-action@v1
      with:
        build: yarn build
        start: yarn start --spa
        wait-on: 'http://localhost:3000'
